packages:
  - packages/ts/**
  - apps/server
  - apps/client_app
  - apps/admin_app
  - apps/workers/*

catalog:
  typescript: 5.7.3
  uuid: ^10.0.0
  "vitest": "~3.0.7"
  "@types/uuid": "^10.0.0"
  "@libsql/client": "^0.14.0"
  hono: 4.7.4
  next: 15.2.4
  eslint-config-next: 15.2.4
  '@cloudflare/workers-types': ^4.20240614.0
  "@cloudflare/vitest-pool-workers": "^0.8.19"
  '@cloudflare/next-on-pages': 1.13.12
  wrangler: ^3.61.0
  zod: 3.24.2
  zod-openapi: 4.2.3
  '@hono/swagger-ui': '^0.5.1'
  '@hono/zod-openapi': '^0.19.6'
  "drizzle-kit": "^0.31.1"
  "drizzle-orm": "^0.43.1"
  "dotenv": "^16.1.4"
  "drizzle-zod": "^0.7.1"
  "tsx": "^4.19.4"
  "@types/node": "^22.15.3"
