#:schema node_modules/wrangler/config-schema.json
name = "track-you-api-keys"
main = "src/index.ts"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

[vars]
TURSO_URL = "libsql://api-key-ishafiul.aws-ap-south-1.turso.io"
