#:schema node_modules/wrangler/config-schema.json
name = "track-you-analytics"
main = "src/index.ts"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

[vars]
TURSO_URL = "libsql://analytics-ishafiul.aws-ap-south-1.turso.io"
