name: track_you_core_platform_interface
description: A common platform interface for the track_you_core plugin.
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
