name: track_you_core_ios
description: iOS implementation of the track_you_core plugin
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    implements: track_you_core
    platforms:
      ios:
        pluginClass: TrackYouCorePlugin
        dartPluginClass: TrackYouCoreIOS

dependencies:
  flutter:
    sdk: flutter
  track_you_core_platform_interface: 0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
