name: track_you_core_ios

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/track_you_core_ios.yaml"
      - "track_you_core_ios/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/track_you_core_ios.yaml"
      - "track_you_core_ios/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.24.0
      working_directory: track_you_core_ios

